In [8]:
for i in range(0,4):
    for j in range(0,4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print()

      * 
    * * 
  * * * 
* * * * 


In [12]:
name=input("enter name")
for i in range(len(name)):
    for j in range(0,i+1):
        print(name[i],end=" ")
    print()

enter namereena
r 
e e 
e e e 
n n n n 
a a a a a 


In [14]:
rec={}
n=int(input("enter number of students:"))
i=1
while i<=n:
    name=input("enter student name:")
    marks=input("enter % marks of student:")
    rec[name]=marks
    i+=1
print("name of the student","  ","% of marks")
for x in rec:
    print("  ",x,"           ",rec[x])

enter number of students:1
enter student name:reena
enter % marks of student:85
name of the student    % of marks
   reena             85


In [15]:
d={100:"mite",200:"shy"}
print(d)

{100: 'mite', 200: 'shy'}


In [16]:
del d[200]

In [17]:
print(d)

{100: 'mite'}


In [19]:
d.clear()

In [20]:
print(d)

{}


In [22]:
d={100:"shy",200:"fre",300:"lrs"}
len(d)

3

In [24]:
word=input("enter any word:")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any word:hhheeeeelllllooooooooooo
h occure 3 times
e occure 5 times
l occure 5 times
o occure 11 times


In [26]:
word=input("enter a sentence:")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if x in vowels:
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter a sentence:my name reena
a occure 2 times
e occure 3 times


In [27]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [30]:
n=[1,2,3,4,5,5,5,5]
print(n.count(4))

1


In [31]:
print(n.index(4))

3


In [33]:
n=[1,2,3,4,5]
n.insert(1,0)
print(n)

[1, 0, 2, 3, 4, 5]


In [34]:
m=[9,8,8,7,6,5]
n.extend(m)

In [35]:
print(m)

[9, 8, 8, 7, 6, 5]


In [36]:
print(n)

[1, 0, 2, 3, 4, 5, 9, 8, 8, 7, 6, 5]


### remove element
n.remove(3)

In [38]:
print(n)

[1, 0, 2, 4, 5, 9, 8, 8, 7, 6, 5]


In [39]:
n.pop()

5

In [40]:
n.reverse()

In [41]:
print(n)

[6, 7, 8, 8, 9, 5, 4, 2, 0, 1]


In [46]:
lst=["reena","asura","kavya","sakshi"]
lst.sort()
print(lst)

['asura', 'kavya', 'reena', 'sakshi']


In [47]:
lst.sort(reverse=True)
print(lst)

['sakshi', 'reena', 'kavya', 'asura']


In [49]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [50]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [51]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [52]:
a=[10,20,30,40]
b=[50,60,70,80]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60, 70, 80]


In [53]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [57]:
x=["mite","mangalore","nitte"]
y=["mite","mangalore","nitte"]
x==y
x!=y
z=["mite","mangalore","nitte"]
x==z

True

In [58]:
m=[10,20,30,40,[50,60,70]]
m[4][1]

60

In [59]:
m[3]

40

In [60]:
m.clear()

In [61]:
n=[1,2,3,4]
print(4 in n)

True


In [62]:
print(8 in n)

False


In [63]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [65]:
words=["mite","mysore","reena","geeta"]
l=[w[0] for w in words]
print(l)

['m', 'm', 'r', 'g']


In [66]:
def times2(var):
    return var*2
ret=times2(2)

In [67]:
print(ret)

4


In [68]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [69]:
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [70]:
import numpy as np
my_lst=[1,2,3]
my_lst
np.array(my_lst)

array([1, 2, 3])

In [71]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [74]:
np.zeros(3)

array([0., 0., 0.])

In [75]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [78]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
np.random.rand(2)

array([0.52747513, 0.36170174])

In [80]:
np.random.rand(5,5)

array([[0.11037504, 0.09034613, 0.55765738, 0.11309533, 0.96856237],
       [0.41450334, 0.86080092, 0.11747205, 0.19552034, 0.09441175],
       [0.33428656, 0.65757674, 0.21266329, 0.01638872, 0.13702059],
       [0.72012053, 0.35090483, 0.12704591, 0.4204594 , 0.77751929],
       [0.04520201, 0.28875877, 0.17639498, 0.33022685, 0.41659782]])

In [81]:
np.random.randn(5,5)

array([[ 1.24020168, -1.41563446, -0.65603299,  0.3208231 ,  0.62640427],
       [-0.71156978, -1.01271311,  0.20028661,  0.69513162,  2.49516744],
       [ 0.08154561, -2.02927034,  0.9297025 , -0.86626029, -1.27929384],
       [-0.07188707, -0.75302148, -0.1616013 ,  0.92510418,  0.63851765],
       [-0.30690516,  0.629353  ,  0.21540212,  0.75283649,  0.30845386]])

In [83]:
ar=np.random.randint(1,100,10)

In [84]:
print(ar)

[70 64 43 11 43 82 45 74 25 22]


In [85]:
arr=np.arange(25)

In [86]:
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
runarr.max()

45

In [88]:
runarr.argmax()

3

In [91]:
arr.shape

(25,)

In [92]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [93]:
arr.reshape(1,25).shape

(1, 25)

In [94]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [95]:
arr.reshape(25,1).shape

(25, 1)

In [96]:
arr.dtype

dtype('int32')

In [97]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [98]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [99]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
arr/arr

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [101]:
1/arr

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [102]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [103]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [104]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [105]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [106]:
np.log(arr)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [108]:
arr=np.arange(0,11)
arr
arr[8]


8

In [109]:
arr[1:5]

array([1, 2, 3, 4])

In [110]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [111]:
arr[0:5]=100

In [112]:
arr=np.arange(0,11)

In [113]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [114]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [115]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [117]:
np.fives(10)

AttributeError: module 'numpy' has no attribute 'fives'

In [118]:
arr[0:10]=5
arr

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 10])

In [120]:
np.arange(10,81,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [121]:
np.linspace(0,8,9)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [124]:
arr=np.arange(9)
runarr=np.random.randint(0,8,10)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
arr=np.arange(25)
runarr=np.random.randint(1,25,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [126]:
arr[arr>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])